include Makefile

.PHONY: ocp-manifests
ocp-manifests: $(RELEASE_DIR) $(KUSTOMIZE) ## Builds openshift specific manifests
	mkdir -p $(RELEASE_DIR)/openshift
	# Build core-components.
	$(KUSTOMIZE) build --load_restrictor=LoadRestrictionsNone config/openshift > $(RELEASE_DIR)/openshift/core-components.yaml
